### ISSUE TITLE
line 13: syntax error near unexpected token

### ISSUE THREAD

**Issue by Futureknows** [LawLawL/Dnscrypt-list-ping-sorting#1]
Sounds like a great script, I am running it as root but after a while I get the following errors:

**/home/user/Downloads/Dnscrypt-list-ping-sorting-master/ping_dnscrypt.py: line 13: syntax error near unexpected token `('
/home/user/Downloads/Dnscrypt-list-ping-sorting-master/ping_dnscrypt.py: line 13: `def mean(list):'**

I wonder if it is because I already have DNSCRYPT running at router level?

**Comment by Futureknows** [comment]
> `
/home/user/Downloads/Dnscrypt-list-ping-sorting-master/ping_dnscrypt.py: line 13: syntax error near unexpected token `('
/home/user/Downloads/Dnscrypt-list-ping-sorting-master/ping_dnscrypt.py: line 13: `def mean(list):'
`

**Comment by Magalame** [comment]
I think it probably comes from the way you might have copy/pasted the code, maybe you should try:
`wget https://raw.githubusercontent.com/LawLawL/Dnscrypt-list-ping-sorting/master/ping_dnscrypt.py`
then
`sudo python3 ping_dnscrypt.py`

**Comment by Futureknows** [comment]
You are expert scholar sir gentleman. I didn't know the python3 command til now.
