### ISSUE TITLE
[FIXED] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [LawLawL/Dnscrypt-list-ping-sorting#2]
Dear Magalame,
Could you be so kind to generate ```.exe``` for the rest of us who use Windows w/o Python?

**Comment by Magalame** [comment]
Indeed!
You can download it there: https://drive.google.com/file/d/0Bxzq1JsVPF3eTFdFOTF6Wk9IbEk/view
Once you install it you can launch it with typing 
`"C:\Program Files\Ping dnscrypt\ping.exe"` 
in the command line. Please keep the quotation signs otherwise it will break.

**Comment by sergeevabc** [comment]
Oh, I thought it would be a portable static executable. Howbeit, it works as expected, but I noticed that it silently skips unpingable yet working servers like ns0.dnscrypt.is (93.95.228.87), which could be probed using tools such as [TCPing][1] and [PSPing][2]. Perhaps a similar ICMP alternative is available in Python.

```
C:\>tcping 93.95.228.87 443

Probing 93.95.228.87:443/tcp - Port is open - time=96.394ms
Probing 93.95.228.87:443/tcp - Port is open - time=88.561ms
Probing 93.95.228.87:443/tcp - Port is open - time=89.069ms
Probing 93.95.228.87:443/tcp - Port is open - time=88.394ms

Ping statistics for 93.95.228.87:443
     4 probes sent.
     4 successful, 0 failed.
Approximate trip times in milli-seconds:
     Minimum = 88.394ms, Maximum = 96.394ms, Average = 90.604ms
```

[1]: https://elifulkerson.com/projects/tcping.php
[2]: https://docs.microsoft.com/en-us/sysinternals/downloads/psping

**Comment by Magalame** [comment]
I can definitely also upload a portable one too: https://drive.google.com/open?id=0Bxzq1JsVPF3eSEhJcDZHbUF0cW8
Also thank you for bringing up this issue, I hadn't realized that. The problem there is that if they're unpingable it's probably because they have shut down ICMP on their server, which I will try to solve by implementing a tcp version of the ping function.

**Comment by Magalame** [comment]
The problem should be solved now

**Comment by sergeevabc** [comment]
Alas, I cannot run this build, it throws error as follows
```
c:\ping_dnscrypt>pingdnscrypt.exe
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 13, in run
ModuleNotFoundError: No module named 'pingdnscrypt__init__'
```

**Comment by Magalame** [comment]
Could you try with the portable version?

**Comment by sergeevabc** [comment]
I did, the quoted error message was output by the portable build [above][1].

[1]: https://github.com/LawLawL/Dnscrypt-list-ping-sorting/issues/2#issuecomment-338242865

**Comment by Magalame** [comment]
Oh I should have been more explicit! There is a newer version: https://drive.google.com/open?id=0Bxzq1JsVPF3eUmczWVdyb3lKdjQ

**Comment by sergeevabc** [comment]
Oh, dear Magalame, something became very wrong, didn’t you notice?
First of all, “Loading the result” hangs for significantly more time before the table is actually rolled out.
Then the top lines of “Merged list” have [irrelevant][1] statements (Mexico, NY… for Russia-based user?).
Let alone “realibility” is distorted, since e.g. Yandex (being a major service) should be 99.9% reliable.
I believe a new ping implementation is to blame, be sure to try [another][2] approaches.
You will know it is done right when the new results will _almost match_ the former, initial ones.

[1]: https://ghostbin.com/paste/yv6dm
[2]: https://github.com/search?l=Python&q=tcp+ping&type=Repositories&utf8=✓

**Comment by Magalame** [comment]
I don't think it's an implementation problem, I find totally reliable results with a user based in Canada: [here](https://ghostbin.com/paste/7dqh2) with about the same results as the initial ones

What's probably happening is that the device you use has a hard time to deal properly with the amount of requests the program generates. Could you try with 
`pingdnscrypt.exe -n 10` ?
it should decrease the number of request by server (to 10) 

The longer time is normal as I increased the delay between each ping to have more reliable result. As I use multithreading (otherwise it would really take a long time) if a lot of pingings are happening at the same time it's no good. 

Thank you for your patience

**Comment by sergeevabc** [comment]
>  device you use has a hard time to deal properly with the amount of requests the program generates

This explains why I had to reboot the router after running this build without arguments and just rebooted again after running with ```-n 10``` as it became totally unresponsive. Results are still not relevant, alas.

**Comment by Magalame** [comment]
What kind of hardware do you use? I'm very surprised it doesn't work as I tried with a raspberry pi and it could handle it without trouble.
There is also a `-s` option which allows you to set a delay (in seconds) between every time the program starts pinging a new server and a `-p` option that set the delay between each individual ping. 
Maybe try with something like `-n 5 -s 0.5 -p 0.1`, it might take some time unfortunately though.

**Comment by LawLawL** [comment]
Was the problem resolved?

**Comment by Magalame** [comment]
Should I close this issue?

**Comment by sergeevabc** [comment]
> Maybe try with something like -n 5 -s 0.5 -p 0.1, it might take some time unfortunately though.

These options let my router to stay afloat without freezing, yet the results are rather dubious.

```
Name                    IP address              ping             reliability    DNSSEC  No log  Location
d0wn-random-ns2         185.14.29.140           0.73    +/-0.0ms        100.0%  yes     yes     Netherlands
d0wn-ru-ns1             91.214.71.181           0.75    +/-0.01ms       100.0%  yes     yes     Russia
d0wn-se-ns1             95.215.44.124           0.76    +/-0.01ms       100.0%  yes     yes     Sweden
d0wn-nl-ns4             31.220.43.105           0.79    +/-0.03ms       100.0%  yes     yes     Netherlands
d0wn-es-ns1             91.142.220.29           0.79    +/-0.0ms        100.0%  yes     yes     Spain
d0wn-lv-ns1             89.111.13.60            0.79    +/-0.0ms        100.0%  yes     yes     Latvia
d0wn-at-ns1             79.133.33.52            0.79    +/-0.01ms       100.0%  yes     yes     Austria
d0wn-fr-ns2             37.187.0.40             0.79    +/-0.01ms       100.0%  yes     yes     France
dnscrypt.eu-dk          77.66.84.233            0.79    +/-0.02ms       100.0%  yes     yes     Denmark
d0wn-is-ns2             93.95.226.165           0.81    +/-0.02ms       100.0%  yes     yes     Iceland
```

Lack of safe network defaults dismayed me, so I wrote [CryptoPing][1] about a month ago.
It is a well-documented Windows batch file that uses features of PSPing and Gawk, the output is as follows.
```
Time      Server                     Privacy    DNSSEC
4.0ms     adguard-dns                yes        no
4.2ms     adguard-dns-family         yes        no
8.4ms     yandex                     no         no
20.2ms    cs-fi                      yes        no
29.0ms    ipredator                  yes        yes
30.0ms    cs-lv                      yes        no
33.5ms    dnscrypt.eu-dk             yes        yes
34.9ms    cs-md                      yes        no
36.7ms    cs-lt                      yes        no
39.8ms    soltysiak                  yes        yes
```

[1]: https://app.box.com/s/a5144laen397pty0lob8d2b50803h3lx
