### ISSUE TITLE
Pinging with your software resulted in 1-3 ms pings. Microsoft ping = 200 ms

### ISSUE THREAD

**Issue by ravenise** [LawLawL/Dnscrypt-list-ping-sorting#3]
This is the windows version of the app. I live in Canada, your software was showing dnscrypt servers in russia to be the lowest latency, a latency of 3 ms or so, this was demonstrated @ 20 pings per server; In a standard test servers in iceland showed a latency of 1.3 milliseconds; this seemed wildly inaccurate so I tested using windows ping, and sure enough I was getting around 200ms  in russia.

Somethings not adding up very well here.

**Comment by Magalame** [comment]
It seems quite strange as I live in Canada and I get accurate results. Try to run it without any option.

**Comment by Magalame** [comment]
No follow up, gets closed
